name: production CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
        
    steps:
    - uses: actions/checkout@v3
        
    - name: 📂 Sync files
      uses:  burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude=".git" --exclude=".github"  --exclude=".ssh"
        path: /
        remote_path: ~/app/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Running Rasa
    - uses: appleboy/ssh-action@v0.1.10
      with:
        host:  ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        command_timeout: 30m
        script: | 
          cd app/
          rasa train
          python3 discord_bot.py &
          rasa run --enable-api --credentials credentials.yml --cors "*" &
          rasa run actions &
          
